-- 코드를 입력하세요
-- 2021년에 가입한 전체 회원들 중
-- PUCHASED_RATIO = 2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수
-- 년을 기준으로 오름차순 > 월을 기준으로 오름차순
SELECT YEAR(OS.SALES_DATE) AS YEAR,
        MONTH(OS.SALES_DATE) AS MONTH,
        COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT OS.USER_ID)
             / (SELECT COUNT(DISTINCT USER_ID) 
                FROM USER_INFO 
                WHERE YEAR(JOINED) = 2021), 1) PURCHASED_RATIO
FROM USER_INFO UI
INNER JOIN ONLINE_SALE OS 
ON UI.USER_ID = OS.USER_ID
WHERE YEAR(UI.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH