-- 코드를 입력하세요
-- 같은 맛의 아이스크림이라도 다른 출하 번호를 갖게 됩니다.
SELECT S.FLAVOR
FROM (SELECT SUM(F.TOTAL_ORDER+J.TOTAL_ORDER) SUM_ORDER, F.FLAVOR
     FROM FIRST_HALF F
     JOIN JULY J
     ON F.FLAVOR = J.FLAVOR
     GROUP BY FLAVOR
     ORDER BY SUM_ORDER DESC) S
LIMIT 3