-- 코드를 입력하세요
SELECT HOUR, COUNT(ANIMAL_ID) COUNT
FROM (-- ROW_NUMBER 는 분석(순위) 함수이기 때문에 OVER 절과 함께 사용
        SELECT (ROW_NUMBER() OVER () - 1) AS HOUR
        FROM ANIMAL_OUTS
        LIMIT 24) AS 24HOURS_NUM_TABLE 
LEFT JOIN ANIMAL_OUTS ON HOUR = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR
