-- '완료된' 중고 거래의 총금액이 70만 원 이상인 사람
-- 총거래금액을 기준으로 오름차순
SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_USER
JOIN USED_GOODS_BOARD
ON USER_ID = WRITER_ID
WHERE STATUS = "DONE"
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC