-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (SELECT I.ANIMAL_ID, I.NAME, I.DATETIME IN_TIME, O.DATETIME OUT_TIME 
      FROM ANIMAL_INS I 
      INNER JOIN ANIMAL_OUTS O
      ON I.ANIMAL_ID = O.ANIMAL_ID) IN_OUT
WHERE IN_TIME > OUT_TIME
ORDER BY IN_TIME